# Generated by Django 4.0.5 on 2022-06-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentsection',
            name='employee_capability',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
