# Generated by Django 4.0.5 on 2022-06-20 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_departmentsection_employee_capability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentsection',
            name='employee_capability',
        ),
    ]
